import { GridMetric, TelemetryPoint, SimulationModule } from "@/types/grid";

export const gridMetricsData: GridMetric[] = [
  {
    id: "active-substations",
    label: "ACTIVE SUBSTATIONS",
    value: "142 / 148",
    unit: "ONLINE",
    status: "optimal",
    delta: "+95.9%",
    deltaType: "positive",
    technicalDetail: "6 nodes scheduled for maintenance",
  },
  {
    id: "total-capacity",
    label: "TOTAL GRID CAPACITY",
    value: "4,850",
    unit: "MW",
    status: "nominal",
    delta: "78% load",
    deltaType: "neutral",
    technicalDetail: "Peak headroom: +1,070 MW",
  },
  {
    id: "current-load",
    label: "CURRENT ACTIVE LOAD",
    value: "3,780",
    unit: "MW",
    status: "nominal",
    delta: "+1.8% vs 1h",
    deltaType: "positive",
    technicalDetail: "Industrial: 52% | Urban: 48%",
  },
  {
    id: "load-factor",
    label: "LOAD FACTOR",
    value: "0.84",
    unit: "COEFF",
    status: "optimal",
    delta: "+0.02 vs ref",
    deltaType: "positive",
    technicalDetail: "Optimal operational window [0.80 - 0.88]",
  },
  {
    id: "stability-index",
    label: "GRID STABILITY INDEX",
    value: "98.6%",
    unit: "SCORE",
    status: "optimal",
    delta: "N-1 Resilient",
    deltaType: "positive",
    technicalDetail: "Dynamic inertia damping active",
  },
  {
    id: "grid-frequency",
    label: "GRID FREQUENCY",
    value: "50.02",
    unit: "Hz",
    status: "optimal",
    delta: "Δ +0.02 Hz",
    deltaType: "positive",
    technicalDetail: "Tolerance bounds: 49.95 - 50.05 Hz",
  },
  {
    id: "active-alerts",
    label: "ACTIVE ALERTS",
    value: "0 CRITICAL",
    unit: "1 ADVISORY",
    status: "warning",
    delta: "Normal state",
    deltaType: "neutral",
    technicalDetail: "Substation Delta-4 thermal monitoring",
  },
];

export const telemetry24hData: TelemetryPoint[] = [
  { time: "00:00", loadMW: 2800, generationMW: 2950, baselineMW: 2750, solarMW: 0, windMW: 1200, thermalMW: 1600, bessMW: 150, frequencyHz: 50.01 },
  { time: "02:00", loadMW: 2600, generationMW: 2720, baselineMW: 2550, solarMW: 0, windMW: 1350, thermalMW: 1250, bessMW: 120, frequencyHz: 50.02 },
  { time: "04:00", loadMW: 2500, generationMW: 2600, baselineMW: 2480, solarMW: 0, windMW: 1400, thermalMW: 1100, bessMW: 100, frequencyHz: 50.00 },
  { time: "06:00", loadMW: 3100, generationMW: 3250, baselineMW: 3000, solarMW: 180, windMW: 1280, thermalMW: 1600, bessMW: 190, frequencyHz: 49.99 },
  { time: "08:00", loadMW: 3850, generationMW: 4000, baselineMW: 3750, solarMW: 650, windMW: 1150, thermalMW: 2050, bessMW: 150, frequencyHz: 50.01 },
  { time: "10:00", loadMW: 4200, generationMW: 4350, baselineMW: 4100, solarMW: 1120, windMW: 980, thermalMW: 2150, bessMW: 100, frequencyHz: 50.03 },
  { time: "12:00", loadMW: 4450, generationMW: 4580, baselineMW: 4350, solarMW: 1450, windMW: 850, thermalMW: 2180, bessMW: 100, frequencyHz: 50.02 },
  { time: "14:00", loadMW: 4300, generationMW: 4420, baselineMW: 4200, solarMW: 1380, windMW: 890, thermalMW: 2050, bessMW: 100, frequencyHz: 50.01 },
  { time: "16:00", loadMW: 4150, generationMW: 4290, baselineMW: 4050, solarMW: 820, windMW: 1100, thermalMW: 2220, bessMW: 150, frequencyHz: 49.98 },
  { time: "18:00", loadMW: 4600, generationMW: 4720, baselineMW: 4500, solarMW: 210, windMW: 1380, thermalMW: 2780, bessMW: 350, frequencyHz: 50.00 },
  { time: "20:00", loadMW: 4350, generationMW: 4480, baselineMW: 4250, solarMW: 0, windMW: 1450, thermalMW: 2750, bessMW: 280, frequencyHz: 50.02 },
  { time: "22:00", loadMW: 3500, generationMW: 3620, baselineMW: 3400, solarMW: 0, windMW: 1320, thermalMW: 2100, bessMW: 200, frequencyHz: 50.01 },
];

export const simulationModulesData: SimulationModule[] = [
  {
    id: "ai-forecast",
    name: "AI Load & Renewable Forecasting",
    tag: "NEURAL TRANSFORMER",
    status: "ONLINE",
    description: "Deep learning spatio-temporal models predicting 24-hour bus-level load profiles and weather-driven renewable fluctuations with 98.2% accuracy.",
    actionLabel: "View 24h Predictions",
    accentColor: "cyan",
    stats: [
      { label: "HORIZON", value: "24h Ahead" },
      { label: "MAPE ERROR", value: "1.42%" },
    ],
  },
  {
    id: "contingency-sim",
    name: "Contingency & Risk Simulation",
    tag: "N-1 / N-2 ENGINE",
    status: "READY",
    description: "Exhaustive transient stability and AC power-flow contingency scans evaluating voltage collapse risks, thermal line overloads, and cascading outages.",
    actionLabel: "Run N-1 Fast Scan",
    accentColor: "amber",
    stats: [
      { label: "SCANNED LINES", value: "348 Branches" },
      { label: "VULNERABILITY", value: "Low (0.04)" },
    ],
  },
  {
    id: "what-if-sandbox",
    name: "What-If Scenario Sandbox",
    tag: "MONTE CARLO",
    status: "READY",
    description: "Interactive boundary-condition testing for extreme heatwaves, sudden generator trips, electric vehicle surge charging, and cyber-physical disturbances.",
    actionLabel: "Launch Scenario Builder",
    accentColor: "emerald",
    stats: [
      { label: "PRESETS", value: "12 Scenarios" },
      { label: "SIM SPEED", value: "< 240 ms" },
    ],
  },
  {
    id: "dispatch-optimization",
    name: "AI Dispatch Optimization",
    tag: "MILP + REINFORCEMENT",
    status: "ONLINE",
    description: "Automated optimal power flow (OPF) algorithms calculating minimal cost, carbon-abated unit commitment, and dynamic battery storage charging schedules.",
    actionLabel: "Compute Optimal Dispatch",
    accentColor: "blue",
    stats: [
      { label: "COST SAVINGS", value: "-4.8%" },
      { label: "CO2 REDUCTION", value: "-12.4 t/h" },
    ],
  },
  {
    id: "scada-stream",
    name: "Real-Time SCADA Telemetry",
    tag: "IEC 61850 / DNP3",
    status: "ONLINE",
    description: "High-frequency phasor measurement unit (PMU) ingestion streaming voltage angles, active/reactive powers, and breaker states at 50 packets/sec.",
    actionLabel: "Inspect Telemetry Feeds",
    accentColor: "emerald",
    stats: [
      { label: "PMU LATENCY", value: "18 ms" },
      { label: "PACKET INTEGRITY", value: "99.999%" },
    ],
  },
];
